apiVersion: v1
kind: Service
metadata:
  name: stomp-cluster-backend-service
spec:
  selector:
    app: stomp-cluster-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080